name: Bug Report (中文)
description: 提交一个bug
title: "[组件名]: "
labels: ["🐞 Bug", "ownerless"]
body:
  - type: markdown
    attributes:
      value: "## 感谢你对xx的贡献"
  - type: markdown
    attributes:
      value: |
        你需要花一些时间填写这份bug报告!
  - type: markdown
    attributes:
      value: "## 在开始之前"
  - type: markdown
    attributes:
      value: |
        为了能在有限的人力下提高解决问题的效率，问题和讨论应该发生在Github issue列表之外，这里只用于提出明确的缺陷或者未支持的特性
  - type: markdown
    attributes:
      value: |
        另外表单中选项请尽可能地完善，足够的信息能大大提高问题解决的效率
  - type: input
    id: version
    attributes:
      label: 版本
      description: 在哪个版本发生了问题
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: 浏览器
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - IE11
        - Others
  - type: input
    id: reproduction
    attributes:
      label: 重现链接
      description: 前往[CodeSandbox](https://codesandbox.io/s/fusion-next-1-x-glk2g6?file=/src/App.js)、[CodePen](https://codepen.io/pen?&editors=0010){:target="_blank"}、[内网Riddle](https://riddle.alibaba-inc.com/riddles/new?code=%7B%22html%22%3A%22%3Cdiv%20id%3D%5C%22mountNode%5C%22%3E%3C%2Fdiv%3E%22%2C%22jsx%22%3A%22%2F%2F%20%E9%BB%98%E8%AE%A4%E6%9C%80%E6%96%B0%E7%9A%84next%E7%89%88%E6%9C%AC%2C%E6%83%B3%E8%A6%81%E6%8C%87%E5%AE%9A%E7%89%B9%E5%AE%9Anext%E7%89%88%E6%9C%AC%2C%E9%80%9A%E8%BF%87%27%40alife%2Fnext%400.1.61%27%E7%9A%84%E6%96%B9%E5%BC%8F%E6%8C%87%E5%AE%9A%5Cn%2F%2F%20%E8%8C%83%E4%BE%8B%E5%A6%82%E4%B8%8B%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8E%BB%E6%8E%89%E6%B3%A8%E9%87%8A%E6%9F%A5%E7%9C%8B%E6%95%88%E6%9E%9C%5Cn%2F%2F%20import%20React%20from%20%27React%27%3B%5Cnimport%20React%20from%20%27react%4016%27%3B%5Cnimport%20ReactDOM%20from%20%27react-dom%4016%27%3B%5Cnimport%20%7B%20Button%20%7D%20from%20%27%40alife%2Fnext%401.x%27%3B%5Cn%5CnReactDOM.render(%3CButton%20type%3D%5C%22primary%5C%22%3E%E6%8C%89%E9%92%AE%3C%2FButton%3E%2C%20mountNode)%3B%5Cn%22%2C%22css%22%3A%22%2F*%20%E6%AD%A4%E5%A4%84%E4%B9%A6%E5%86%99%E6%A0%B7%E5%BC%8F%E4%BB%A3%E7%A0%81%EF%BC%8C%E6%94%AF%E6%8C%81%20less%20*%2F%5Cn%5Cn%40import%20%27~%40alife%2Fnext%401.x%2Fdist%2Fnext.css%27%3B%5Cn%22%2C%22json%22%3A%22%7B%5Cn%20%20%5C%22name%5C%22%3A%20%5C%22riddle%5C%22%2C%5Cn%20%20%5C%22dependencies%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22react%5C%22%3A%20%5C%2216.x%5C%22%2C%5Cn%20%20%20%20%5C%22react-dom%5C%22%3A%20%5C%2216.x%5C%22%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D&amdType=common){:target="_blank"}创建最小化复现场景
      placeholder: https://codesandbox.io/s/...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
