name: Bug Report (中文)
description: 提交一个bug
title: "[组件名]: "
labels: ["🐞 Bug", "ownerless"]
body:
  - type: markdown
    attributes:
      value: "## 感谢你对xx的贡献"
  - type: markdown
    attributes:
      value: |
        你需要花一些时间填写这份bug报告!
  - type: markdown
    attributes:
      value: "## 在开始之前"
  - type: markdown
    attributes:
      value: |
        为了能在有限的人力下提高解决问题的效率,这里只用于提出明确的缺陷或者未支持的特性
  - type: markdown
    attributes:
      value: |
        另外表单中选项请尽可能地完善，充足的信息能大大提高问题解决的效率
  - type: input
    id: version
    attributes:
      label: 组件库版本
      description: 在哪个版本发生了问题
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: 浏览器
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - IE11
        - Others
      default: 1
  - type: input
    id: reproduction
    attributes:
      label: 重现链接
      placeholder: https://codesandbox.io/s/...
      description: 前往 [CodeSandbox](https://codesandbox.io/s/fusion-design-demo-rpr46k) 创建最小化复现场景
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 重现步骤
      description: 请输入简洁清晰的重现步骤，以便我们更快速地定位问题
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期结果
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: 其它补充说明
